### ISSUE TITLE
Error when creating a datastore in regions other than global

### ISSUE THREAD

**Issue by agutta** [GoogleCloudPlatform/dfcx-scrapi#168]
Scrapi tool to create datastore with global as region works but not for other regions.

## Expected Behavior
Should create a datastore in us region

## Current Behavior
InvalidArgument: 400 Location must be "global", got "us".

## Possible Solution
Should create a datastore in region given by caller.

## Steps to Reproduce

1. Follow the code in go/scrapi-data-stores
2. just change location to us

## Detailed Description
Trying Vertex Search and Conversation features with scrapi tool.

**Comment by kmaphoenix** [comment]
Quick Update:

I've identified the issue is on the Discovery Engine API side, not with SCRAPI.  
The API is blocking any value other than `global`, which means it will fail when you try `us`.   

I've filed a bug internally for the issue.  
We'll keep this item open for now and track it, but there's no action item on our side for now, and that means unfortunately any users wishing to take this action via API are blocked.

![image](https://github.com/GoogleCloudPlatform/dfcx-scrapi/assets/13949241/3a96c386-aba3-4a43-85d0-e5acaaa9726d)
