### ISSUE TITLE
Request to add Playbook version and environment feature similar to CX flows.

### ISSUE THREAD

**Issue by krishnapadm** [GoogleCloudPlatform/dfcx-scrapi#214]

**Comment by kmaphoenix** [comment]
I've added support for creating playbook versions via the API.  
However, the current proto for Versions and Environments in DFCX does not support Playbook IDs right now.

I've filed this as an internal bug.  
Until that bug is fixed, you won't be able to assign playbook versions to environments in DFCX.  
You will only be able to create playbook versions via the API.

**Comment by Sharath106** [comment]
Hi Team,

Could you please confirm if the issue with playbook version has been resolved? 
We're currently tying to promote the playbook in DFCX , but the version seems to get skipped.

 WARNING  Skipping playbook version: projects/project_name/locations/locations/agents/agent_id/playbooks/playbook_id/versions/1
