### ISSUE TITLE
Missing update_entity_type function in core.entity_types

### ISSUE THREAD

**Issue by LDLucien** [GoogleCloudPlatform/dfcx-scrapi#4]
I found this project quite useful for beginners like me to access dialogflow cx API on using python. 
But I think the update_entity_type function in core-entity_types is missed, so I would like to know if you plan to add it in the future?

Best!

**Comment by kmaphoenix** [comment]
Hi @LDLucien !

Great catch! We will definitely add `update_entity_type` in one of the upcoming patches.

I saw your previous comment re: `update_mask` as well.
I agree, this isn't very well documented, but perhaps I can provide some intuition on its use.

The `update_mask` field is exposed in the lower level library and corresponds to the fields in the underlying resource object that you are trying to modify. For example, if you are trying to modify/update an Entity Type object, you would look at the attributes of the [Entity Type class](https://github.com/googleapis/python-dialogflow-cx/blob/main/google/cloud/dialogflowcx_v3beta1/types/entity_type.py#L35).

So let's say you wanted to update the `display_name` of your Entity Type object. 
The `update_mask` field would expect that you pass in a kwarg of `display_name='My New Entity Name'` so that your Entity Type object would be updated.
In the lower level library, this requires that you build these kwargs through a Proto mask before passing them to `update_mask`.

In the SCRAPI library, we try to simplify this and allow you to pass them in as kwargs and we'll handle the rest.
The final outcome should be something like this:

```
e = EntityTypes()
e.update_entity_type(<entity_id>, <entity_obj>, display_name='My New Entity Name')
```

Hope this helps!
We'll have this patched soon.

**Comment by LDLucien** [comment]
> Hi @LDLucien !
> 
> Great catch! We will definitely add `update_entity_type` in one of the upcoming patches.
> 
> I saw your previous comment re: `update_mask` as well.
> I agree, this isn't very well documented, but perhaps I can provide some intuition on its use.
> 
> The `update_mask` field is exposed in the lower level library and corresponds to the fields in the underlying resource object that you are trying to modify. For example, if you are trying to modify/update an Entity Type object, you would look at the attributes of the [Entity Type class](https://github.com/googleapis/python-dialogflow-cx/blob/main/google/cloud/dialogflowcx_v3beta1/types/entity_type.py#L35).
> 
> So let's say you wanted to update the `display_name` of your Entity Type object.
> The `update_mask` field would expect that you pass in a kwarg of `display_name='My New Entity Name'` so that your Entity Type object would be updated.
> In the lower level library, this requires that you build these kwargs through a Proto mask before passing them to `update_mask`.
> 
> In the SCRAPI library, we try to simplify this and allow you to pass them in as kwargs and we'll handle the rest.
> The final outcome should be something like this:
> 
> ```
> e = EntityTypes()
> e.update_entity_type(<entity_id>, <entity_obj>, display_name='My New Entity Name')
> ```
> 
> Hope this helps!
> We'll have this patched soon.

Thanks so much @kmaphoenix !
I think you explain it very well. Luckily, after posting this issue, I took an afternoon and solved it. The `update_intent` function in `intents.py` was quite helpful for me to understand the `update_mask`  more. There are around 6 thousand entities I need to update, and this library really saved my life!  

The code I use is something listed below. And I think I actually did not use the `update_mask`, did I? But it works and the update result looks nice and normal. Besides that, I will try your solution, it looks simpler and clearer.
```python
entity_type = types.entity_type.EntityType()
setattr(entity_type, 'name', <entity_name>)
setattr(entity_type,'display_name', <Entity Type Name>)
setattr(entity_type, 'kind', 'KIND_MAP')
for i,synonyms in entity_list,synonyms_list:
    entity_example =  {'value':i,'synonyms':{synonyms}}
    entity_type.entities.append(entity_example)
e = EntityTypes()
e.update_entity_type(entity_id=<entity_id>, obj=entity_type)
```
Thanks for your reply. I love this library and look forward to seeing the new features in the future!

**Comment by kmaphoenix** [comment]
@LDLucien  [v1.0.4](https://github.com/GoogleCloudPlatform/dfcx-scrapi/releases/tag/1.0.4) was released today and we've patched the `update_entity_type` function as suggested [here](https://github.com/GoogleCloudPlatform/dfcx-scrapi/blob/main/src/dfcx_scrapi/core/entity_types.py#L166).

Re: your code, you're correct in that you are not using the `update_mask` but you're essentially getting the same result because you're creating the entire Entity Type object and then pushing that to the Agent. Still a perfectly working solution!

Let me know if you have any other questions, otherwise closing this issue.
